### ISSUE TITLE
Remove unneeded parts of Form and Report files

### ISSUE THREAD

**Issue by bkp7** [x-ware-ltd/access-scc-addin#28]
The following sections within the Form and Report files are installation specific (relating to printers etc.) or are not used at import time. These parts change each time and make tracking changes difficult.

The items to be removed are:
- GUID
- PrtMip
- PrtDevMode
- PrtDevModeW
- PrtDevNames
- PrtDevNamesW

When removing always remove whole lines.

For each of these sections there are no subsections so simply search to 'End' will work. However in order to ensure the correct 'end' has been found I suggest checking that the number of leading spaces (indentation) matches the header of the section.

**Comment by gilbertbw** [comment]
Fixed by @bkp7  in #29
